Global:
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/vitstr_none_ce/
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 2000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: ppocr/utils/EN_symbol_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_vitstr.txt
Optimizer:
  class: Adadelta
  epsilon: 1.0e-08
  rho: 0.95
  clip_norm: 5.0
  lr: 1.0
LRScheduler: null
Model:
  model_type: rec
  algorithm: ViTSTR
  in_channels: 1
  Transform: null
  Backbone:
    class: ViTSTR
    scale: tiny
  Neck:
    class: SequenceEncoder
    encoder_type: reshape
  Head:
    class: CTCHead
Loss:
  class: CELoss
  with_all: true
  ignore_index: 0
PostProcessor:
  class: ViTSTRLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: ViTSTRLabelEncode
        ignore_index: 0
      - class: GrayRecResizeImg
        image_shape:
          - 224
          - 224
        resize_type: PIL
        inter_type: Image.BICUBIC
        scale: false
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 48
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/evaluation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: ViTSTRLabelEncode
        ignore_index: 0
      - class: GrayRecResizeImg
        image_shape:
          - 224
          - 224
        resize_type: PIL
        inter_type: Image.BICUBIC
        scale: false
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 256
    num_workers: 2
