Global:
  use_gpu: true
  epoch_num: 6
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/rec/seed
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: ppocr/utils/EN_symbol_dict.txt
  max_text_length: 100
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_seed.txt
Optimizer:
  class: Adadelta
  weight_deacy: 0.0
  momentum: 0.9
LRScheduler:
  class: Piecewise
  decay_epochs:
    - 4
    - 5
  values:
    - 1.0
    - 0.1
    - 0.01
Model:
  model_type: rec
  algorithm: SEED
  Transform:
    class: STN_ON
    tps_inputsize:
      - 32
      - 64
    tps_outputsize:
      - 32
      - 100
    num_control_points: 20
    tps_margins:
      - 0.05
      - 0.05
    stn_activation: none
  Backbone:
    class: ResNet_ASTER
  Head:
    class: AsterHead
    sDim: 512
    attDim: 512
    max_len_labels: 100
Loss:
  class: AsterLoss
PostProcessor:
  class: SEEDLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
  is_filter: true
Train:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training/
    transforms:
      - class: Fasttext
        path: ./cc.en.300.bin
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SEEDLabelEncode
      - class: RecResizeImg
        character_dict_path: null
        image_shape:
          - 3
          - 64
          - 256
        padding: false
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
          - fast_label
  DataLoader:
    shuffle: true
    batch_size: 256
    drop_last: true
    num_workers: 6
Eval:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/evaluation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SEEDLabelEncode
      - class: RecResizeImg
        character_dict_path: null
        image_shape:
          - 3
          - 64
          - 256
        padding: false
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: true
    batch_size: 256
    num_workers: 4
