Global:
  use_gpu: true
  epoch_num: 10
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/rec/r45_abinet/
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: ./pretrain_models/abinet_vl_pretrained
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: null
  character_type: en
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_abinet.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.99
  clip_norm: 20.0
LRScheduler:
  class: Piecewise
  decay_epochs:
    - 6
  values:
    - 0.0001
    - 1.0e-05
Model:
  model_type: rec
  algorithm: ABINet
  in_channels: 3
  Transform: null
  Backbone:
    class: ResNet45
  Head:
    class: ABINetHead
    use_lang: true
    iter_size: 3
Loss:
  class: CELoss
  ignore_index: 100
PostProcessor:
  class: ABINetLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: ABINetRecAug
      - class: ABINetLabelEncode
        ignore_index: 100
      - class: ABINetRecResizeImg
        image_shape:
          - 3
          - 32
          - 128
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 96
    drop_last: true
    num_workers: 4
Eval:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/evaluation/
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: ABINetLabelEncode
        ignore_index: 100
      - class: ABINetRecResizeImg
        image_shape:
          - 3
          - 32
          - 128
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 256
    num_workers: 4
    use_shared_memory: false
