Global:
  use_gpu: true
  epoch_num: 5
  log_window_size: 20
  log_batch_step: 20
  save_model_dir: ./output/rec/rec_r31_robustscanner/
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: ppocr/utils/dict90.txt
  max_text_length: 40
  infer_mode: false
  use_space_char: false
  rm_symbol: true
  save_res_path: ./output/rec/predicts_robustscanner.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
LRScheduler:
  class: PiecewiseLR
  decay_epochs:
    - 3
    - 4
  values:
    - 0.001
    - 0.0001
    - 1.0e-05
Model:
  model_type: rec
  algorithm: RobustScanner
  Transform: null
  Backbone:
    class: ResNet31
    init_type: KaimingNormal
  Head:
    class: RobustScannerHead
    enc_outchannles: 128
    hybrid_dec_rnn_layers: 2
    hybrid_dec_dropout: 0
    position_dec_rnn_layers: 2
    start_idx: 91
    mask: true
    padding_idx: 92
    encode_value: false
    max_text_length: 40
Loss:
  class: SARLoss
PostProcessor:
  class: SARLabelDecode
Metric:
  class: RecMetric
  is_filter: true
Train:
  Dataset:
    class: LMDBDataSet
    root: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SARLabelEncode
      - class: RobustScannerRecResizeImg
        image_shape:
          - 3
          - 48
          - 48
          - 160
        width_downsample_ratio: 0.25
        max_text_length: 40
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - valid_ratio
          - word_positons
  DataLoader:
    shuffle: true
    batch_size: 64
    drop_last: true
    num_workers: 8
    use_shared_memory: false
Eval:
  Dataset:
    class: LMDBDataSet
    root: ./train_data/data_lmdb_release/evaluation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SARLabelEncode
      - class: RobustScannerRecResizeImg
        image_shape:
          - 3
          - 48
          - 48
          - 160
        max_text_length: 40
        width_downsample_ratio: 0.25
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - valid_ratio
          - word_positons
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 64
    num_workers: 4
    use_shared_memory: false
