Global:
  use_gpu: true
  epoch_num: 20
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/rec/svtr/
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: null
  character_type: en
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_svtr_tiny.txt
Optimizer:
  class: AdamW
  beta1: 0.9
  beta2: 0.99
  eps: 1.0e-08
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr: 0.0005
LRScheduler:
  class: CosineAnnealingWarmRestarts
  T_0: 2
Model:
  model_type: rec
  algorithm: SVTR
  Transform:
    class: STN_ON
    tps_inputsize:
      - 32
      - 64
    tps_outputsize:
      - 32
      - 100
    num_control_points: 20
    tps_margins:
      - 0.05
      - 0.05
    stn_activation: none
  Backbone:
    class: SVTRNet
    img_size:
      - 32
      - 100
    out_char_num: 25
    out_channels: 192
    patch_merging: Conv
    embed_dim:
      - 64
      - 128
      - 256
    depth:
      - 3
      - 6
      - 3
    num_heads:
      - 2
      - 4
      - 8
    mixer:
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
    local_mixer:
      - - 7
        - 11
      - - 7
        - 11
      - - 7
        - 11
    last_stage: true
    prenorm: false
  Neck:
    class: SequenceEncoder
    encoder_type: reshape
  Head:
    class: CTCHead
Loss:
  class: CTCLoss
PostProcessor:
  class: CTCLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: LMDBDataSet
    root: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SVTRRecAug
        aug_type: 0
      - class: CTCLabelEncode
      - class: SVTRRecResizeImg
        image_shape:
          - 3
          - 64
          - 256
        padding: false
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 512
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: LMDBDataSet
    root: ./train_data/data_lmdb_release/evaluation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: CTCLabelEncode
      - class: SVTRRecResizeImg
        image_shape:
          - 3
          - 64
          - 256
        padding: false
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 256
    num_workers: 2
