Global:
  use_gpu: true
  epoch_num: 21
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/nrtr/
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 2000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: ppocr/utils/EN_symbol_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_nrtr.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.99
  clip_norm: 5.0
  lr: 0.0005
LRScheduler:
  class: CosineAnnealingWarmRestarts
  T_0: 2
Model:
  model_type: rec
  algorithm: NRTR
  in_channels: 1
  Transform: null
  Backbone:
    class: MTB
    cnn_num: 2
  Head:
    class: Transformer
    d_model: 512
    num_encoder_layers: 6
    beam_size: -1
Loss:
  class: CELoss
  smoothing: true
PostProcessor:
  class: NRTRLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: NRTRLabelEncode
      - class: GrayRecResizeImg
        image_shape:
          - 100
          - 32
        resize_type: PIL
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 512
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/evaluation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: NRTRLabelEncode
      - class: GrayRecResizeImg
        image_shape:
          - 100
          - 32
        resize_type: PIL
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 256
    num_workers: 4
    use_shared_memory: false
