Global:
  use_gpu: true
  epoch_num: 5
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./sar_rec
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 2000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  character_dict_path: ppocr/utils/dict90.txt
  max_text_length: 30
  infer_mode: false
  use_space_char: false
  rm_symbol: true
  save_res_path: ./output/rec/predicts_sar.txt
Optimizer:
  class: Adam
  beta1: 0.9
  beta2: 0.999
LRScheduler:
  class: Piecewise
  decay_epochs:
    - 3
    - 4
  values:
    - 0.001
    - 0.0001
    - 1.0e-05
Model:
  model_type: rec
  algorithm: SAR
  Transform: null
  Backbone:
    class: ResNet31
  Head:
    class: SARHead
Loss:
  class: SARLoss
PostProcessor:
  class: SARLabelDecode
Metric:
  class: RecMetric
Train:
  Dataset:
    class: SimpleDataSet
    label_file_list:
      - ./train_data/train_list.txt
    data_dir: ./train_data/
    ratio_list: 1.0
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SARLabelEncode
      - class: SARRecResizeImg
        image_shape:
          - 3
          - 48
          - 48
          - 160
        width_downsample_ratio: 0.25
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - valid_ratio
  DataLoader:
    shuffle: true
    batch_size: 64
    drop_last: true
    num_workers: 8
    use_shared_memory: false
Eval:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/evaluation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SARLabelEncode
      - class: SARRecResizeImg
        image_shape:
          - 3
          - 48
          - 48
          - 160
        width_downsample_ratio: 0.25
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - valid_ratio
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 64
    num_workers: 4
    use_shared_memory: false
