Global:
  use_gpu: true
  epoch_num: 8
  log_window_size: 200
  log_batch_step: 200
  save_model_dir: ./output/rec/r45_visionlan
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: true
  infer_img: doc/imgs_words/en/word_2.png
  character_dict_path: null
  max_text_length: 25
  training_step: LA
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_visionlan.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  clip_norm: 20.0
  group_lr: true
  training_step: LA
LRScheduler:
  class: PiecewiseLR
  decay_epochs:
    - 6
  values:
    - 0.0001
    - 1.0e-05
Model:
  model_type: rec
  algorithm: VisionLAN
  Transform: null
  Backbone:
    class: ResNet45
    strides:
      - 2
      - 2
      - 2
      - 1
      - 1
  Head:
    class: VLHead
    n_layers: 3
    n_position: 256
    n_dim: 512
    max_text_length: 25
    training_step: LA
Loss:
  class: VLLoss
  mode: LA
  weight_res: 0.5
  weight_mas: 0.5
PostProcessor:
  class: VLLabelDecode
Metric:
  class: RecMetric
  is_filter: true
Train:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: ABINetRecAug
      - class: VLLabelEncode
      - class: VLRecResizeImg
        image_shape:
          - 3
          - 64
          - 256
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - label_res
          - label_sub
          - label_id
          - length
  DataLoader:
    shuffle: true
    batch_size: 220
    drop_last: true
    num_workers: 4
Eval:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/validation/
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: VLLabelEncode
      - class: VLRecResizeImg
        image_shape:
          - 3
          - 64
          - 256
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - label_res
          - label_sub
          - label_id
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 64
    num_workers: 4
