Global:
  use_gpu: true
  epoch_num: 6
  log_window_size: 50
  log_batch_step: 50
  save_model_dir: ./output/rec/rec_r32_gaspin_bilstm_att/
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: ./ppocr/utils/dict/spin_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_r32_gaspin_bilstm_att.txt
Optimizer:
  class: AdamW
  beta1: 0.9
  beta2: 0.999
LRScheduler:
  class: PiecewiseLR
  decay_epochs:
    - 3
    - 4
    - 5
  values:
    - 0.001
    - 0.0003
    - 9.0e-05
    - 2.7e-05
  clip_norm: 5
Model:
  model_type: rec
  algorithm: SPIN
  in_channels: 1
  Transform:
    class: GA_SPIN_Transformer
    offsets: true
    default_type: 6
    loc_lr: 0.1
    stn: true
  Backbone:
    class: ResNet32
    out_channels: 512
  Neck:
    class: SequenceEncoder
    encoder_type: cascadernn
    hidden_size: 256
    out_channels:
      - 256
      - 512
    with_linear: true
  Head:
    class: SPINAttentionHead
    hidden_size: 256
Loss:
  class: SPINAttentionLoss
  ignore_index: 0
PostProcessor:
  class: SPINLabelDecode
  use_space_char: false
Metric:
  class: RecMetric
  main_indicator: acc
  is_filter: true
Train:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/ic15_data/
    label_file_list:
      - ./train_data/ic15_data/rec_gt_train.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SPINLabelEncode
      - class: SPINRecResizeImg
        image_shape:
          - 100
          - 32
        interpolation: 2
        mean:
          - 127.5
        std:
          - 127.5
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 8
    drop_last: true
    num_workers: 4
Eval:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/ic15_data
    label_file_list:
      - ./train_data/ic15_data/rec_gt_test.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SPINLabelEncode
      - class: SPINRecResizeImg
        image_shape:
          - 100
          - 32
        interpolation: 2
        mean:
          - 127.5
        std:
          - 127.5
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 8
    num_workers: 2
