Global:
  use_gpu: true
  epoch_num: 72
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/rec/r34_vd_tps_bilstm_ctc/
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: null
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_r34_vd_tps_bilstm_ctc.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.0005
LRScheduler:
  class: ConstantLR
Model:
  model_type: rec
  algorithm: STARNet
  Transform:
    class: TPS
    num_fiducial: 20
    loc_lr: 0.1
    model_name: large
  Backbone:
    class: ResNet
    layers: 34
  Neck:
    class: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    class: CTCHead
    fc_decay: 0
Loss:
  class: CTCLoss
PostProcessor:
  class: CTCLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 100
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 256
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/validation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 100
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 256
    num_workers: 4
