Global:
  use_gpu: true
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/ic15/
  save_epoch_step: 3
  # evaluation is run every 2000 iterations
  eval_batch_step: [ 0, 2000 ]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir: ./
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ppocr/utils/en_dict.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_ic15.txt

Optimizer:
  class: Adam
  beta1: 0.9
  beta2: 0.999
  lr: 0.0005
LRScheduler:



Model:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    class: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    class: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    class: CTCHead
    fc_decay: 0

Loss:
  class: CTCLoss

PostProcessor:
  class: CTCLabelDecode

Metric:
  class: RecMetric
  main_indicator: acc

Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/ic15_data/
    label_file_list: [ "./train_data/ic15_data/rec_gt_train.txt" ]
    transforms:
      - class: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - class: CTCLabelEncode # Class handling label
      - class: RecResizeImg
        image_shape: [ 3, 32, 100 ]
      - class: KeepKeys
        keep_keys: [ 'image', 'label', 'length' ] # dataloader will return list in this order
  DataLoader:
    shuffle: True
    batch_size: 256
    drop_last: True
    num_workers: 8
    use_shared_memory: False

Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/ic15_data
    label_file_list: [ "./train_data/ic15_data/rec_gt_test.txt" ]
    transforms:
      - class: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - class: CTCLabelEncode # Class handling label
      - class: RecResizeImg
        image_shape: [ 3, 32, 100 ]
      - class: KeepKeys
        keep_keys: [ 'image', 'label', 'length' ] # dataloader will return list in this order
  DataLoader:
    shuffle: False
    drop_last: False
    batch_size: 256
    num_workers: 4
    use_shared_memory: False
