Global:
  use_gpu: True
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/mv3_none_bilstm_ctc/
  save_epoch_step: 3
  # evaluation is run every 2000 iterations
  eval_batch_step: [ 0, 2000 ]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path:
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_mv3_none_bilstm_ctc.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr: 0.0005
LRScheduler:



Model:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcessor:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  Dataset:
    name: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training/
    transforms:
      - name: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - name: CTCLabelEncode # Class handling label
      - name: RecResizeImg
        image_shape: [ 3, 32, 100 ]
      - name: KeepKeys
        keep_keys: [ 'image', 'label', 'length' ] # dataloader will return list in this order
  DataLoader:
    shuffle: False
    batch_size: 256
    drop_last: True
    num_workers: 8

Eval:
  Dataset:
    name: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/validation/
    transforms:
      - name: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - name: CTCLabelEncode # Class handling label
      - name: RecResizeImg
        image_shape: [ 3, 32, 100 ]
      - name: KeepKeys
        keep_keys: [ 'image', 'label', 'length' ] # dataloader will return list in this order
  DataLoader:
    shuffle: False
    drop_last: False
    batch_size: 256
    num_workers: 4
