Global:
  use_gpu: true
  epoch_num: 72
  log_window_size: 20
  log_batch_step: 5
  save_model_dir: ./output/rec/srn_new
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 5000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: null
  max_text_length: 25
  num_heads: 8
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_srn.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  clip_norm: 10.0
  lr: 0.0001
LRScheduler:
  class: ConstantLR
Model:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform: null
  Backbone:
    class: ResNetFPN
  Head:
    class: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512
Loss:
  class: SRNLoss
PostProcessor:
  class: SRNLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: LMDBDataSet
    root: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SRNLabelEncode
      - class: SRNRecResizeImg
        image_shape:
          - 1
          - 64
          - 256
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
          - encoder_word_pos
          - gsrm_word_pos
          - gsrm_slf_attn_bias1
          - gsrm_slf_attn_bias2
  DataLoader:
    shuffle: false
    batch_size: 64
    drop_last: false
    num_workers: 4
Eval:
  Dataset:
    class: LMDBDataSet
    root: ./train_data/data_lmdb_release/validation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: SRNLabelEncode
      - class: SRNRecResizeImg
        image_shape:
          - 1
          - 64
          - 256
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
          - encoder_word_pos
          - gsrm_word_pos
          - gsrm_slf_attn_bias1
          - gsrm_slf_attn_bias2
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 32
    num_workers: 4
