Global:
  use_gpu: true
  epoch_num: 72
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/rec/ic15/
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: ./
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: ppocr/utils/en_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_ic15.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.0005
LRScheduler:
  class: ConstantLR
Model:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    class: MobileNetV3Rec
    scale: 0.5
    model_name: large
  Neck:
    class: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    class: CTCHead
    fc_decay: 0
Loss:
  class: CTCLoss
PostProcessor:
  class: CTCLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/ic15_data/
    label_file_list:
      - ./train_data/ic15_data/rec_gt_train.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 100
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 256
    drop_last: true
    num_workers: 8
    use_shared_memory: false
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/ic15_data
    label_file_list:
      - ./train_data/ic15_data/rec_gt_test.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 100
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 256
    num_workers: 4
    use_shared_memory: false
