Global:
  use_gpu: true
  epoch_num: 8
  log_window_size: 20
  log_batch_step: 5
  save_model_dir: ./output/rec/pren_new
  save_epoch_step: 3
  eval_batch_step:
    - 4000
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: null
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_pren.txt
Optimizer:
  class: Adadelta
LRScheduler:
  class: PiecewiseLR
  decay_epochs:
    - 2
    - 5
    - 7
  values:
    - 0.5
    - 0.1
    - 0.01
    - 0.001
Model:
  model_type: rec
  algorithm: PREN
  in_channels: 3
  Backbone:
    class: EfficientNetB3_PREN
  Neck:
    class: PRENFPN
    n_r: 5
    d_model: 384
    max_len: 25
    dropout: 0.1
  Head:
    class: PRENHead
Loss:
  class: PRENLoss
PostProcessor:
  class: PRENLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: LMDBDataSet
    root: ./train_data/data_lmdb_release/training/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: PRENLabelEncode
      - class: RecAug
      - class: PRENResizeImg
        image_shape:
          - 64
          - 256
      - class: KeepKeys
        keep_keys:
          - image
          - label
  DataLoader:
    shuffle: true
    batch_size: 128
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: LMDBDataSet
    root: ./train_data/data_lmdb_release/validation/
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: PRENLabelEncode
      - class: PRENResizeImg
        image_shape:
          - 64
          - 256
      - class: KeepKeys
        keep_keys:
          - image
          - label
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 64
    num_workers: 8
