Global:
  use_gpu: True
  epoch_num: 6
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: ./output/rec/rec_resnet_rfl_att/
  save_epoch_step: 1
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [ 0, 5000 ]
  cal_metric_during_train: True
  pretrained_model: ./pretrain_models/rec_resnet_rfl_visual/best_accuracy.pdparams
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path:
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/rec_resnet_rfl.txt


Optimizer:
  class: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0
  clip_norm_global: 5.0
LRScheduler:
  class: Piecewise
  decay_epochs: [ 3, 4, 5 ]
  values: [ 0.001, 0.0003, 0.00009, 0.000027 ]

Model:
  model_type: rec
  algorithm: RFL
  in_channels: 1
  Transform:
    class: TPS
    num_fiducial: 20
    loc_lr: 1.0
    model_name: large
  Backbone:
    class: ResNetRFL
    use_cnt: True
    use_seq: True
  Neck:
    class: RFAdaptor
    use_v2s: True
    use_s2v: True
  Head:
    class: RFLHead
    in_channels: 512
    hidden_size: 256
    batch_max_legnth: 25
    out_channels: 38
    use_cnt: True
    use_seq: True

Loss:
  class: RFLLoss
  # ignore_index: 0

PostProcessor:
  class: RFLLabelDecode

Metric:
  class: RecMetric
  main_indicator: acc

Train:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/training
    transforms:
      - class: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - class: RFLLabelEncode # Class handling label
      - class: RFLRecResizeImg
        image_shape: [ 1, 32, 100 ]
        padding: false
        interpolation: 2
      - class: KeepKeys
        keep_keys: [ 'image', 'label', 'length', 'cnt_label' ] # dataloader will return list in this order
  DataLoader:
    shuffle: True
    batch_size: 64
    drop_last: True
    num_workers: 8

Eval:
  Dataset:
    class: LMDBDataSet
    data_dir: ./train_data/data_lmdb_release/validation/
    transforms:
      - class: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - class: RFLLabelEncode # Class handling label
      - class: RFLRecResizeImg
        image_shape: [ 1, 32, 100 ]
        padding: false
        interpolation: 2
      - class: KeepKeys
        keep_keys: [ 'image', 'label', 'length', 'cnt_label' ] # dataloader will return list in this order
  DataLoader:
    shuffle: False
    drop_last: False
    batch_size: 256
    num_workers: 8
