Global:
  use_gpu: true
  epoch_num: 400
  log_window_size: 20
  log_batch_step: 20
  save_model_dir: ./output/SLANet_ch
  save_epoch_step: 400
  eval_batch_step:
    - 0
    - 331
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: ./output/SLANet_ch/infer
  use_visualdl: false
  infer_img: ppstructure/docs/table/table.jpg
  character_dict_path: ppocr/utils/dict/table_structure_dict_ch.txt
  character_type: en
  max_text_length: 500
  box_format: xy4
  infer_mode: false
  use_sync_bn: true
  save_res_path: output/infer
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  clip_norm: 5.0
  lr: 0.001
LRScheduler:
  class: ConstantLR
Model:
  model_type: table
  algorithm: SLANet
  Backbone:
    class: PPLCNet
    scale: 1.0
    pretrained: true
    use_ssld: true
  Neck:
    class: CSPPAN
    out_channels: 96
  Head:
    class: SLAHead
    hidden_size: 256
    max_text_length: 500
    loc_reg_num: 8
Loss:
  class: SLALoss
  structure_weight: 1.0
  loc_weight: 2.0
  loc_loss: smooth_l1
PostProcessor:
  class: TableLabelDecode
  merge_no_span_structure: true
Metric:
  class: TableMetric
  main_indicator: acc
  compute_bbox_metric: false
  loc_reg_num: 8
  box_format: xy4
  del_thead_tbody: true
Train:
  Dataset:
    class: PubTabDataSet
    root: train_data/table/train/
    label_file_list:
      - train_data/table/train.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: TableLabelEncode
        learn_empty_box: false
        merge_no_span_structure: true
        replace_empty_cell_token: false
        loc_reg_num: 8
        max_text_length: 500
      - class: TableBoxEncode
        in_box_format: xy4
        out_box_format: xy4
      - class: ResizeTableImage
        max_len: 488
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: PaddingTableImage
        size:
          - 488
          - 488
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - structure
          - bboxes
          - bbox_masks
          - shape
  DataLoader:
    shuffle: true
    batch_size: 48
    drop_last: true
    num_workers: 1
Eval:
  Dataset:
    class: PubTabDataSet
    root: train_data/table/val/
    label_file_list:
      - train_data/table/val.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: TableLabelEncode
        learn_empty_box: false
        merge_no_span_structure: true
        replace_empty_cell_token: false
        loc_reg_num: 8
        max_text_length: 500
      - class: TableBoxEncode
        in_box_format: xy4
        out_box_format: xy4
      - class: ResizeTableImage
        max_len: 488
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: PaddingTableImage
        size:
          - 488
          - 488
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - structure
          - bboxes
          - bbox_masks
          - shape
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 48
    num_workers: 1
