Global:
  use_gpu: true
  epoch_num: 17
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/table_master/
  save_epoch_step: 17
  eval_batch_step:
    - 0
    - 6259
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: output/table_master/infer
  use_visualdl: false
  infer_img: ppstructure/docs/table/table.jpg
  save_res_path: ./output/table_master
  character_dict_path: ppocr/utils/dict/table_master_structure_dict.txt
  infer_mode: false
  max_text_length: 500
  box_format: xywh
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.001
LRScheduler:
  class: MultiStepDecay
  milestones:
    - 12
    - 15
  gamma: 0.1
  warmup_epoch: 0.02
Model:
  model_type: table
  algorithm: TableMaster
  Backbone:
    class: TableResNetExtra
    gcb_config:
      ratio: 0.0625
      headers: 1
      att_scale: false
      fusion_type: channel_add
      layers:
        - false
        - true
        - true
        - true
    layers:
      - 1
      - 2
      - 5
      - 3
  Head:
    class: TableMasterHead
    hidden_size: 512
    headers: 8
    dropout: 0
    d_ff: 2024
    max_text_length: 500
    loc_reg_num: 4
Loss:
  class: TableMasterLoss
  ignore_index: 42
PostProcessor:
  class: TableMasterLabelDecode
  box_shape: pad
  merge_no_span_structure: true
Metric:
  class: TableMetric
  main_indicator: acc
  compute_bbox_metric: false
  box_format: xywh
Train:
  Dataset:
    class: PubTabDataSet
    data_dir: train_data/table/pubtabnet/train/
    label_file_list:
      - train_data/table/pubtabnet/PubTabNet_2.0.0_train.jsonl
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: TableMasterLabelEncode
        learn_empty_box: false
        merge_no_span_structure: true
        replace_empty_cell_token: true
        loc_reg_num: 4
        max_text_length: 500
      - class: ResizeTableImage
        max_len: 480
        resize_bboxes: true
      - class: PaddingTableImage
        size:
          - 480
          - 480
      - class: TableBoxEncode
        in_box_format: xywh
        out_box_format: xywh
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.5
          - 0.5
          - 0.5
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - structure
          - bboxes
          - bbox_masks
          - shape
  DataLoader:
    shuffle: true
    batch_size: 10
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: PubTabDataSet
    data_dir: train_data/table/pubtabnet/val/
    label_file_list:
      - train_data/table/pubtabnet/PubTabNet_2.0.0_val.jsonl
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: TableMasterLabelEncode
        learn_empty_box: false
        merge_no_span_structure: true
        replace_empty_cell_token: true
        loc_reg_num: 4
        max_text_length: 500
      - class: ResizeTableImage
        max_len: 480
        resize_bboxes: true
      - class: PaddingTableImage
        size:
          - 480
          - 480
      - class: TableBoxEncode
        in_box_format: xywh
        out_box_format: xywh
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.5
          - 0.5
          - 0.5
        std:
          - 0.5
          - 0.5
          - 0.5
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - structure
          - bboxes
          - bbox_masks
          - shape
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 10
    num_workers: 8
