Global:
  use_gpu: true
  epoch_num: 400
  log_window_size: 20
  log_batch_step: 5
  save_model_dir: ./output/table_mv3/
  save_epoch_step: 400
  eval_batch_step:
    - 0
    - 400
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: ppstructure/docs/table/table.jpg
  save_res_path: output/table_mv3
  character_dict_path: ppocr/utils/dict/table_structure_dict.txt
  character_type: en
  max_text_length: 500
  box_format: xyxy
  infer_mode: false
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  clip_norm: 5.0
  lr: 0.001
LRScheduler:
  class: ConstantLR
Model:
  model_type: table
  algorithm: TableAttn
  Backbone:
    class: MobileNetV3
    scale: 1.0
    model_name: small
    disable_se: true
  Head:
    class: TableAttentionHead
    hidden_size: 256
    max_text_length: 500
    loc_reg_num: 4
Loss:
  class: TableAttentionLoss
  structure_weight: 100.0
  loc_weight: 10000.0
PostProcessor:
  class: TableLabelDecode
Metric:
  class: TableMetric
  main_indicator: acc
  compute_bbox_metric: false
Train:
  Dataset:
    class: PubTabDataSet
    data_dir: train_data/table/pubtabnet/train/
    label_file_list:
      - train_data/table/pubtabnet/PubTabNet_2.0.0_train.jsonl
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: TableLabelEncode
        learn_empty_box: false
        merge_no_span_structure: false
        replace_empty_cell_token: false
        loc_reg_num: 4
        max_text_length: 500
      - class: TableBoxEncode
      - class: ResizeTableImage
        max_len: 488
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: PaddingTableImage
        size:
          - 488
          - 488
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - structure
          - bboxes
          - bbox_masks
          - shape
  DataLoader:
    shuffle: true
    batch_size: 48
    drop_last: true
    num_workers: 1
Eval:
  Dataset:
    class: PubTabDataSet
    data_dir: train_data/table/pubtabnet/val/
    label_file_list:
      - train_data/table/pubtabnet/PubTabNet_2.0.0_val.jsonl
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: TableLabelEncode
        learn_empty_box: false
        merge_no_span_structure: false
        replace_empty_cell_token: false
        loc_reg_num: 4
        max_text_length: 500
      - class: TableBoxEncode
      - class: ResizeTableImage
        max_len: 488
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: PaddingTableImage
        size:
          - 488
          - 488
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - structure
          - bboxes
          - bbox_masks
          - shape
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 48
    num_workers: 1
