Global:
  use_gpu: true
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/det_r50_vd/
  save_epoch_step: 1200
  # evaluation is run every 2000 iterations
  eval_batch_step: [ 0,2000 ]
  cal_metric_during_train: False
  pretrained_model: ./pretrain_models/ResNet50_vd_ssld_pretrained
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Model:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    class: ResNet_vd
    layers: 50
  Neck:
    class: DBFPN
    out_channels: 256
  Head:
    class: DBHead
    k: 50

Loss:
  class: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  class: Adam
  beta1: 0.9
  beta2: 0.999
  lr: 0.001
LRScheduler:



PostProcessor:
  class: DBPostProcess
  thresh: 0.3
  box_thresh: 0.7
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  class: DetMetric
  main_indicator: hmean

Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list: [ 1.0 ]
    transforms:
      - class: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - class: DetLabelEncode # Class handling label
      - class: IaaAugment
        augmenter_args:
          - { 'type': Fliplr, 'args': { 'p': 0.5 } }
          - { 'type': Affine, 'args': { 'rotate': [ -10, 10 ] } }
          - { 'type': Resize, 'args': { 'size': [ 0.5, 3 ] } }
      - class: EastRandomCropData
        size: [ 640, 640 ]
        max_tries: 50
        keep_ratio: true
      - class: MakeBorderMap
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
      - class: MakeShrinkMap
        shrink_ratio: 0.4
        min_text_size: 8
      - class: NormalizeImage
        scale: 1./255.
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
        order: 'hwc'
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys: [ 'image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask' ] # the order of the dataloader list
  DataLoader:
    shuffle: True
    drop_last: False
    batch_size: 16
    num_workers: 4

Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - class: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - class: DetLabelEncode # Class handling label
      - class: DetResizeForTest
        image_shape: [ 736, 1280 ]
      - class: NormalizeImage
        scale: 1./255.
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
        order: 'hwc'
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys: [ 'image', 'shape', 'polys', 'ignore_tags' ]
  DataLoader:
    shuffle: False
    drop_last: False
    batch_size: 1 # must be 1
    num_workers: 8
