Global:
  use_gpu: true
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./output/det_r50_drrg_ctw/
  save_epoch_step: 100
  # evaluation is run every 1260 iterations
  eval_batch_step: [ 37800, 1260 ]
  cal_metric_during_train: False
  pretrained_model: ./pretrain_models/ResNet50_vd_ssld_pretrained.pdparams
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_drrg/predicts_drrg.txt


Model:
  model_type: det
  algorithm: DRRG
  Transform:
  Backbone:
    name: ResNet_vd
    layers: 50
  Neck:
    name: FPN_UNet
    in_channels: [ 256, 512, 1024, 2048 ]
    out_channels: 32
  Head:
    name: DRRGHead
    in_channels: 32
    text_region_thr: 0.3
    center_region_thr: 0.4
Loss:
  name: DRRGLoss

Optimizer:
  name: Momentum
  momentum: 0.9
  lr: 0.028
LRScheduler:
  name: DecayLearningRate
  
  epochs: 1200
  factor: 0.9
  end_lr: 0.0000001
  weight_decay: 0.0001

PostProcessor:
  name: DRRGPostprocess
  link_thr: 0.8

Metric:
  name: DetFCEMetric
  main_indicator: hmean

Train:
  Dataset:
    name: SimpleDataSet
    data_dir: ./train_data/ctw1500/imgs/
    label_file_list:
      - ./train_data/ctw1500/imgs/training.txt
    transforms:
      - name: DecodeImage # load image
          img_mode: BGR
          channel_first: False
          ignore_orientation: True
      - name: DetLabelEncode # Class handling label
      - name: ColorJitter
          brightness: 0.12549019607843137
          saturation: 0.5
      - name: RandomScaling
      - name: RandomCropFlip
          crop_ratio: 0.5
      - name: RandomCropPolyInstances
          crop_ratio: 0.8
          min_side_ratio: 0.3
      - name: RandomRotatePolyInstances
          rotate_ratio: 0.5
          max_angle: 60
          pad_with_fixed_color: False
      - name: SquareResizePad
          target_size: 800
          pad_ratio: 0.6
      - name: IaaAugment
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
      - name: DRRGTargets
      - name: NormalizeImage
          scale: 1./255.
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
          order: 'hwc'
      - name: ToCHWImage
      - name: KeepKeys
          keep_keys: [ 'image', 'gt_text_mask', 'gt_center_region_mask', 'gt_mask',
                       'gt_top_height_map', 'gt_bot_height_map', 'gt_sin_map',
                       'gt_cos_map', 'gt_comp_attribs' ] # dataloader will return list in this order
  DataLoader:
    shuffle: True
    drop_last: False
    batch_size: 4
    num_workers: 8

Eval:
  Dataset:
    name: SimpleDataSet
    data_dir: ./train_data/ctw1500/imgs/
    label_file_list:
      - ./train_data/ctw1500/imgs/test.txt
    transforms:
      - name: DecodeImage # load image
          img_mode: BGR
          channel_first: False
          ignore_orientation: True
      - name: DetLabelEncode # Class handling label
      - name: DetResizeForTest
          limit_type: 'min'
          limit_side_len: 640
      - name: NormalizeImage
          scale: 1./255.
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
          order: 'hwc'
      - name: Pad
      - name: ToCHWImage
      - name: KeepKeys
          keep_keys: [ 'image', 'shape', 'polys', 'ignore_tags' ]
  DataLoader:
    shuffle: False
    drop_last: False
    batch_size: 1 # must be 1
    num_workers: 2
