Global:
  use_gpu: true
  epoch_num: 600
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/det_ct/
  save_epoch_step: 10
  eval_batch_step:
    - 0
    - 1000
  metric_during_train: false
  pretrained_model: ./pretrain_models/ResNet18_vd_pretrained.pdparams
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img623.jpg
  save_res_path: ./output/det_ct/predicts_ct.txt
Model:
  model_type: det
  algorithm: CT
  Transform: null
  Backbone:
    class: ResNet_vd
    layers: 18
  Neck:
    class: CTFPN
  Head:
    class: CT_Head
    in_channels: 512
    hidden_dim: 128
    num_classes: 3
Loss:
  class: CTLoss
Optimizer:
  class: Adam
  lr: 0.001
LRScheduler:
  class: LinearLR
  end_lr: 0.0
  epochs: 600
  step_each_epoch: 1254
  power: 0.9
PostProcessor:
  class: CTPostProcess
  box_type: poly
Metric:
  class: CTMetric
  main_indicator: f_score
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/total_text/train
    label_file_list:
      - ./train_data/total_text/train/train.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: CTLabelEncode
      - class: RandomScale
      - class: MakeShrink
      - class: GroupRandomHorizontalFlip
      - class: GroupRandomRotate
      - class: GroupRandomCropPadding
      - class: MakeCentripetalShift
      - class: ColorJitter
        brightness: 0.125
        saturation: 0.5
      - class: ToCHWImage
      - class: NormalizeImage
      - class: KeepKeys
        keep_keys:
          - image
          - gt_kernel
          - training_mask
          - gt_instance
          - gt_kernel_instance
          - training_mask_distance
          - gt_distance
  DataLoader:
    shuffle: true
    drop_last: true
    batch_size: 4
    num_workers: 8
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/total_text/test
    label_file_list:
      - ./train_data/total_text/test/test.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: CTLabelEncode
      - class: ScaleAlignedShort
      - class: NormalizeImage
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - texts
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 2
