Global:
  use_gpu: true
  epoch_num: 1500
  log_window_size: 20
  log_batch_step: 20
  save_model_dir: ./output/det_r50_dcn_fce_ctw/
  save_epoch_step: 100
  eval_batch_step:
    - 0
    - 835
  metric_during_train: false
  pretrained_model: ./pretrain_models/ResNet50_vd_ssld_pretrained
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_fce/predicts_fce.txt
Model:
  model_type: det
  algorithm: FCE
  Transform: null
  Backbone:
    class: ResNet_vd
    layers: 50
    dcn_stage:
      - false
      - true
      - true
      - true
    out_indices:
      - 1
      - 2
      - 3
  Neck:
    class: FCEFPN
    out_channels: 256
    has_extra_convs: false
    extra_stage: 0
  Head:
    class: FCEHead
    fourier_degree: 5
Loss:
  class: FCELoss
  fourier_degree: 5
  num_sample: 50
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.0001
LRScheduler:
  class: ConstantLR
PostProcessor:
  class: FCEPostProcess
  scales:
    - 8
    - 16
    - 32
  alpha: 1.0
  beta: 1.0
  fourier_degree: 5
  box_type: poly
Metric:
  class: DetFCEMetric
  main_indicator: hmean
Train:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/ctw1500/imgs/
    label_file_list:
      - ./train_data/ctw1500/imgs/training.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
        ignore_orientation: true
      - class: DetLabelEncode
      - class: ColorJitter
        brightness: 0.142
        saturation: 0.5
        contrast: 0.5
      - class: RandomScaling
      - class: RandomCropFlip
        crop_ratio: 0.5
      - class: RandomCropPolyInstances
        crop_ratio: 0.8
        min_side_ratio: 0.3
      - class: RandomRotatePolyInstances
        rotate_ratio: 0.5
        max_angle: 30
        pad_with_fixed_color: false
      - class: SquareResizePad
        target_size: 800
        pad_ratio: 0.6
      - class: IaaAugment
        augmenter_args:
          - type: Fliplr
            args:
              p: 0.5
      - class: FCENetTargets
        fourier_degree: 5
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - p3_maps
          - p4_maps
          - p5_maps
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 6
    num_workers: 8
Eval:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/ctw1500/imgs/
    label_file_list:
      - ./train_data/ctw1500/imgs/test.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
        ignore_orientation: true
      - class: DetLabelEncode
      - class: DetResizeForTest
        limit_type: min
        limit_side_len: 736
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: Pad
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - ignore_tags
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 2
