Global:
  use_gpu: true
  use_xpu: false
  use_mlu: false
  epoch_num: 1200
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/db_mv3/
  save_epoch_step: 1200
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: false
  pretrained_model: ./pretrain_models/MobileNetV3_large_x0_5_pretrained
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt
Model:
  model_type: det
  algorithm: DB
  Transform: null
  Backbone:
    class: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    class: DBFPN
    out_channels: 256
  Head:
    class: DBHead
    k: 50
Loss:
  class: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Optimizer:
  class: Adam
  betas:
    - 0.9
    - 0.999
  lr: 0.001
LRScheduler: null
PostProcessor:
  class: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Metric:
  class: DetMetric
  main_indicator: hmean
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: IaaAugment
        augmenter_args:
          - type: Fliplr
            args:
              p: 0.5
          - type: Affine
            args:
              rotate:
                - -10
                - 10
          - type: Resize
            args:
              size:
                - 0.5
                - 3
      - class: EastRandomCropData
        size:
          - 640
          - 640
        max_tries: 50
        keep_ratio: true
      - class: MakeBorderMap
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
      - class: MakeShrinkMap
        shrink_ratio: 0.4
        min_text_size: 8
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - threshold_map
          - threshold_mask
          - shrink_map
          - shrink_mask
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 16
    num_workers: 8
    use_shared_memory: true
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: DetResizeForTest
        image_shape:
          - 736
          - 1280
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - ignore_tags
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 8
    use_shared_memory: true
