Global:
  debug: false
  use_gpu: true
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/det_r50_icdar15/
  save_epoch_step: 200
  eval_batch_step:
    - 0
    - 2000
  cal_metric_during_train: false
  pretrained_model: ./pretrain_models/ResNet50_dcn_asf_synthtext_pretrained
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
Model:
  model_type: det
  algorithm: DB++
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
    dcn_stage: [ False, True, True, True ]
  Neck:
    name: DBFPN
    out_channels: 256
    use_asf: True
  Head:
    name: DBHead
    k: 50
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: BCELoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Optimizer:
  name: Momentum
  momentum: 0.9
  lr: 0.007
LRScheduler:
  name: DecayLearningRate
  
  epochs: 1000
  factor: 0.9
  end_lr: 0
  weight_decay: 0.0001
PostProcessor:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
  det_box_type: 'quad' # 'quad' or 'poly'
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  Dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list:
      - 1.0
    transforms:
      - name: DecodeImage
        img_mode: BGR
        channel_first: false
      - name: DetLabelEncode null
      - name: IaaAugment
        augmenter_args:
          - type: Fliplr
          args:
            p: 0.5
            - type: Affine
          args:
            rotate:
              - -10
              - 10
            - type: Resize
          args:
            size:
              - 0.5
              - 3
      - name: EastRandomCropData
        size:
          - 640
          - 640
        max_tries: 10
        keep_ratio: true
      - name: MakeShrinkMap
        shrink_ratio: 0.4
        min_text_size: 8
      - name: MakeBorderMap
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
      - name: NormalizeImage
        scale: 1./255.
        mean:
          - 0.48109378172549
          - 0.45752457890196
          - 0.40787054090196
        std:
          - 1.0
          - 1.0
          - 1.0
        order: hwc
      - name: ToCHWImage null
      - name: KeepKeys
        keep_keys:
          - image
          - threshold_map
          - threshold_mask
          - shrink_map
          - shrink_mask
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 4
    num_workers: 8
Eval:
  Dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - name: DecodeImage
        img_mode: BGR
        channel_first: false
      - name: DetLabelEncode null
      - name: DetResizeForTest
        image_shape:
          - 1152
          - 2048
      - name: NormalizeImage
        scale: 1./255.
        mean:
          - 0.48109378172549
          - 0.45752457890196
          - 0.40787054090196
        std:
          - 1.0
          - 1.0
          - 1.0
        order: hwc
      - name: ToCHWImage null
      - name: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - ignore_tags
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 2
profiler_options: null
