Global:
  use_gpu: true
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/det_r50_vd_pse/
  save_epoch_step: 600
  eval_batch_step:
    - 0
    - 125
  cal_metric_during_train: false
  pretrained_model: ./pretrain_models/ResNet50_vd_ssld_pretrained
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_pse/predicts_pse.txt
Model:
  model_type: det
  algorithm: PSE
  Transform: null
  Backbone:
    class: ResNet_vd
    layers: 50
  Neck:
    class: FPN
    out_channels: 256
  Head:
    class: PSEHead
    hidden_dim: 256
    out_channels: 7
Loss:
  class: PSELoss
  alpha: 0.7
  ohem_ratio: 3
  kernel_sample_mask: pred
  reduction: none
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.0001
LRScheduler:
  class: Step
  step_size: 200
  gamma: 0.1
PostProcessor:
  class: PSEPostProcess
  thresh: 0
  box_thresh: 0.85
  min_area: 16
  box_type: quad
  scale: 1
Metric:
  class: DetMetric
  main_indicator: hmean
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: ColorJitter
        brightness: 0.12549019607843137
        saturation: 0.5
      - class: IaaAugment
        augmenter_args:
          - type: Resize
            args:
              size:
                - 0.5
                - 3
          - type: Fliplr
            args:
              p: 0.5
          - type: Affine
            args:
              rotate:
                - -10
                - 10
      - class: MakePseGt
        kernel_num: 7
        min_shrink_ratio: 0.4
        size: 640
      - class: RandomCropImgMask
        size:
          - 640
          - 640
        main_key: gt_text
        crop_keys:
          - image
          - gt_text
          - gt_kernels
          - mask
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - gt_text
          - gt_kernels
          - mask
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 8
    num_workers: 8
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: DetResizeForTest
        limit_side_len: 736
        limit_type: min
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - ignore_tags
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 8
