Global:
  use_gpu: true
  epoch_num: 5000
  log_smooth_window: 20
  print_batch_step: 2
  save_model_dir: ./output/sast_r50_vd_ic15/
  save_epoch_step: 1000
  eval_batch_step:
    - 4000
    - 5000
  cal_metric_during_train: false
  pretrained_model: ./pretrain_models/ResNet50_vd_ssld_pretrained
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  save_res_path: ./output/sast_r50_vd_ic15/predicts_sast.txt
Model:
  model_type: det
  algorithm: SAST
  Transform: null
  Backbone:
    class: ResNet_SAST
    layers: 50
  Neck:
    class: SASTFPN
    with_cab: true
  Head:
    class: SASTHead
Loss:
  class: SASTLoss
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.001
LRScheduler:
  class: ConstantLR
PostProcessor:
  class: SASTPostProcess
  score_thresh: 0.5
  sample_pts_num: 2
  nms_thresh: 0.2
  expand_scale: 1.0
  shrink_ratio_of_width: 0.3
Metric:
  class: DetMetric
  main_indicator: hmean
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/icdar2013/train_label_json.txt
      - ./train_data/icdar2015/train_label_json.txt
      - ./train_data/icdar17_mlt_latin/train_label_json.txt
      - ./train_data/coco_text_icdar_4pts/train_label_json.txt
    ratio_list:
      - 0.1
      - 0.45
      - 0.3
      - 0.15
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: SASTProcessTrain
        image_shape:
          - 512
          - 512
        min_crop_side_ratio: 0.3
        min_crop_size: 24
        min_text_size: 4
        max_text_size: 512
      - class: KeepKeys
        keep_keys:
          - image
          - score_map
          - border_map
          - training_mask
          - tvo_map
          - tco_map
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 4
    num_workers: 4
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: DetResizeForTest
        resize_long: 1536
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - ignore_tags
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 2
