Global:
  use_gpu: true
  epoch_num: 10000
  log_window_size: 20
  log_batch_step: 2
  save_model_dir: ./output/east_mv3/
  save_epoch_step: 1000
  eval_batch_step:
    - 4000
    - 5000
  metric_during_train: false
  pretrained_model: ./pretrain_models/MobileNetV3_large_x0_5_pretrained
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: null
  save_res_path: ./output/det_east/predicts_east.txt
Model:
  model_type: det
  algorithm: EAST
  Transform: null
  Backbone:
    class: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    class: EASTFPN
    model_name: small
  Head:
    class: EASTHead
    model_name: small
Loss:
  class: EASTLoss
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
LRScheduler:
  class: ConstantLR
PostProcessor:
  class: EASTPostProcess
  score_thresh: 0.8
  cover_thresh: 0.1
  nms_thresh: 0.2
Metric:
  class: DetMetric
  main_indicator: hmean
Train:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: EASTProcessTrain
        image_shape:
          - 512
          - 512
        background_ratio: 0.125
        min_crop_side_ratio: 0.1
        min_text_size: 10
      - class: KeepKeys
        keep_keys:
          - image
          - score_map
          - geo_map
          - training_mask
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 16
    num_workers: 8
Eval:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: DetResizeForTest
        limit_side_len: 2400
        limit_type: max
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - ignore_tags
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 2
