Global:
  use_gpu: true
  epoch_num: 60
  log_window_size: 20
  log_batch_step: 50
  save_model_dir: ./output/kie_5/
  save_epoch_step: 50
  eval_batch_step:
    - 0
    - 80
  load_static_weights: false
  metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  class_path: ./train_data/wildreceipt/class_list.txt
  infer_img: ./train_data/wildreceipt/1.txt
  save_res_path: ./output/sdmgr_kie/predicts_kie.txt
  img_scale:
    - 1024
    - 512
Model:
  model_type: kie
  algorithm: SDMGR
  Transform: null
  Backbone:
    class: Kie_backbone
  Head:
    class: SDMGRHead
Loss:
  class: SDMGRLoss
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.001
LRScheduler:
  class: PiecewiseLR
  decay_epochs:
    - 60
    - 80
    - 100
  values:
    - 0.001
    - 0.0001
    - 1.0e-05
  warmup_epoch: 2
PostProcessor: null
Metric:
  class: KIEMetric
  main_indicator: hmean
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/wildreceipt/
    label_file_list:
      - ./train_data/wildreceipt/wildreceipt_train.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: NormalizeImage
        scale: 1
        mean:
          - 123.675
          - 116.28
          - 103.53
        std:
          - 58.395
          - 57.12
          - 57.375
        order: hwc
      - class: KieLabelEncode
        character_dict_path: ./train_data/wildreceipt/dict.txt
        class_path: ./train_data/wildreceipt/class_list.txt
      - class: KieResize
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - relations
          - texts
          - points
          - labels
          - tag
          - shape
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 4
    num_workers: 4
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/wildreceipt
    label_file_list:
      - ./train_data/wildreceipt/wildreceipt_test.txt
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: KieLabelEncode
        character_dict_path: ./train_data/wildreceipt/dict.txt
      - class: KieResize
      - class: NormalizeImage
        scale: 1
        mean:
          - 123.675
          - 116.28
          - 103.53
        std:
          - 58.395
          - 57.12
          - 57.375
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - relations
          - texts
          - points
          - labels
          - tag
          - ori_image
          - ori_boxes
          - shape
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 4
