Global:
  use_gpu: true
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/pgnet_r50_vd_totaltext/
  save_epoch_step: 10
  eval_batch_step:
    - 0
    - 1000
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  infer_visual_type: EN
  valid_set: totaltext
  save_res_path: ./output/pgnet_r50_vd_totaltext/predicts_pgnet.txt
  character_dict_path: ppocr/utils/ic15_dict.txt
  character_type: EN
  max_text_length: 50
  max_text_nums: 30
  tcl_len: 64
Model:
  model_type: e2e
  algorithm: PGNet
  Transform: null
  Backbone:
    class: ResNet
    layers: 50
  Neck:
    class: PGFPN
  Head:
    class: PGHead
    character_dict_path: ppocr/utils/ic15_dict.txt
Loss:
  class: PGLoss
  tcl_bs: 64
  max_text_length: 50
  max_text_nums: 30
  pad_num: 36
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.001
LRScheduler:
  class: Cosine
  warmup_epoch: 50
PostProcessor:
  class: PGPostProcess
  score_thresh: 0.5
  mode: fast
  point_gather_mode: align
Metric:
  class: E2EMetric
  mode: A
  gt_mat_dir: ./train_data/total_text/gt
  character_dict_path: ppocr/utils/ic15_dict.txt
  main_indicator: f_score_e2e
Train:
  Dataset:
    class: PGDataSet
    data_dir: ./train_data/total_text/train
    label_file_list:
      - ./train_data/total_text/train/train.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: E2ELabelEncodeTrain
      - class: PGProcessTrain
        batch_size: 14
        use_resize: true
        use_random_crop: false
        min_crop_size: 24
        min_text_size: 4
        max_text_size: 512
        point_gather_mode: align
      - class: KeepKeys
        keep_keys:
          - images
          - tcl_maps
          - tcl_label_maps
          - border_maps
          - direction_maps
          - training_masks
          - label_list
          - pos_list
          - pos_mask
  DataLoader:
    shuffle: true
    drop_last: true
    batch_size: 14
    num_workers: 16
Eval:
  Dataset:
    class: PGDataSet
    data_dir: ./train_data/total_text/test
    label_file_list:
      - ./train_data/total_text/test/test.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: E2ELabelEncodeTest
      - class: E2EResizeForTest
        max_side_len: 768
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - texts
          - ignore_tags
          - img_id
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 2
