Global:
  use_gpu: true
  epoch_num: 200
  log_window_size: 10
  log_batch_step: 10
  save_model_dir: ./output/re_layoutlmv2_xfund_zh
  save_epoch_step: 2000
  eval_batch_step:
    - 0
    - 19
  metric_during_train: false
  save_infer_dir: null
  use_visualdl: false
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_21.jpg
  save_res_path: ./output/re_layoutlmv2_xfund_zh/res/
Model:
  model_type: kie
  algorithm: LayoutLMv2
  Transform: null
  Backbone:
    class: LayoutLMv2ForRe
    pretrained: true
    checkpoints: null
Loss:
  class: LossFromOutput
  key: loss
  reduction: mean
Optimizer:
  class: AdamW
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10
  lr: 5.0e-05
LRScheduler:
  class: ConstantLR
  warmup_epoch: 10
PostProcessor:
  class: VQAReTokenLayoutLMPostProcess
Metric:
  class: VQAReTokenMetric
  main_indicator: hmean
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: train_data/XFUND/zh_train/image
    label_file_list:
      - train_data/XFUND/zh_train/train.json
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: VQATokenLabelEncode
        contains_re: true
        algorithm: LayoutLMv2
        class_path: train_data/XFUND/class_list_xfun.txt
      - class: VQATokenPad
        max_seq_len: 512
        return_attention_mask: true
      - class: VQAReTokenRelation
      - class: VQAReTokenChunk
        max_seq_len: 512
      - class: Resize
        size:
          - 224
          - 224
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - input_ids
          - bbox
          - attention_mask
          - token_type_ids
          - image
          - entities
          - relations
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 8
    num_workers: 8
    collate_fn: ListCollator
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: train_data/XFUND/zh_val/image
    label_file_list:
      - train_data/XFUND/zh_val/val.json
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: VQATokenLabelEncode
        contains_re: true
        algorithm: LayoutLMv2
        class_path: train_data/XFUND/class_list_xfun.txt
      - class: VQATokenPad
        max_seq_len: 512
        return_attention_mask: true
      - class: VQAReTokenRelation
      - class: VQAReTokenChunk
        max_seq_len: 512
      - class: Resize
        size:
          - 224
          - 224
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - input_ids
          - bbox
          - attention_mask
          - token_type_ids
          - image
          - entities
          - relations
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 8
    num_workers: 8
    collate_fn: ListCollator
