 Global:
  use_gpu: true
  epoch_num: 1200
  log_window_size: 20
  log_batch_step: 2
  save_model_dir: ./output/ch_db_mv3/
  save_epoch_step: 1200
  eval_batch_step:
    - 3000
    - 2000
  metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt
  use_amp: false
  amp_level: O2
  amp_custom_black_list:
    - exp
Model:
  class: DistillationModel
  algorithm: Distillation
  model_type: det
  Models:
    Teacher:
      pretrained: ./pretrain_models/ch_ppocr_server_v2.0_det_train/best_accuracy
      freeze_params: true
      return_all_feats: false
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        class: ResNet_vd
        layers: 18
      Neck:
        class: DBFPN
        out_channels: 256
      Head:
        class: DBHead
        k: 50
    Student:
      pretrained: null
      freeze_params: false
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        class: MobileNetV3
        scale: 0.5
        model_name: large
        disable_se: true
      Neck:
        class: DBFPN
        out_channels: 96
      Head:
        class: DBHead
        k: 50
    Student2:
      pretrained: null
      freeze_params: false
      return_all_feats: false
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        class: MobileNetV3
        scale: 0.5
        model_name: large
        disable_se: true
      Neck:
        class: DBFPN
        out_channels: 96
      Head:
        class: DBHead
        k: 50
Loss:
  class: CombinedLoss
  loss_config_list:
    - DistillationDilaDBLoss:
        weight: 1.0
        model_name_pairs:
          - - Student
            - Teacher
          - - Student2
            - Teacher
        key: maps
        balance_loss: true
        main_loss_type: DiceLoss
        alpha: 5
        beta: 10
        ohem_ratio: 3
    - DistillationDMLLoss:
        maps_name: thrink_maps
        weight: 1.0
        model_name_pairs:
          - Student
          - Student2
        key: maps
    - DistillationDBLoss:
        weight: 1.0
        model_name_list:
          - Student
          - Student2
        balance_loss: true
        main_loss_type: DiceLoss
        alpha: 5
        beta: 10
        ohem_ratio: 3
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.001
LRScheduler:
  class: CosineAnnealingWarmRestarts
  T_0: 2
PostProcessor:
  class: DistillationDBPostProcess
  model_name:
    - Student
    - Student2
    - Teacher
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Metric:
  class: DistillationMetric
  base_metric_name: DetMetric
  main_indicator: hmean
  key: Student
Train:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: CopyPaste
      - class: IaaAugment
        augmenter_args:
          - type: Fliplr
            args:
              p: 0.5
          - type: Affine
            args:
              rotate:
                - -10
                - 10
          - type: Resize
            args:
              size:
                - 0.5
                - 3
      - class: EastRandomCropData
        size:
          - 960
          - 960
        max_tries: 50
        keep_ratio: true
      - class: MakeBorderMap
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
      - class: MakeShrinkMap
        shrink_ratio: 0.4
        min_text_size: 8
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - threshold_map
          - threshold_mask
          - shrink_map
          - shrink_mask
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 8
    num_workers: 4
Eval:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode
      - class: DetResizeForTest
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - shape
          - polys
          - ignore_tags
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 1
    num_workers: 2
