Global:
  use_gpu: true
  epoch_num: 500
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/sr/sr_tsrn_transformer_strock/
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 1000
  metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_infer_dir: sr_output
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_52.png
  character_dict_path: ./train_data/srdata/english_decomposition.txt
  max_text_length: 100
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/sr/predicts_gestalt.txt
Optimizer:
  class: Adam
  betas: 
    - 0.5
    - 0.999
  clip_norm: 0.25
LRScheduler:
  class: ConstantLR
Model:
  model_type: sr
  algorithm: Gestalt
  Transform:
    class: TSRN
    STN: true
    infer_mode: false
Loss:
  class: StrokeFocusLoss
  character_dict_path: ./train_data/srdata/english_decomposition.txt
PostProcessor:
  class: None
Metric:
  class: SRMetric
  main_indicator: all
Train:
  Dataset:
    class: LMDBDataSetSR
    data_dir: ./train_data/srdata/train
    transforms:
      - class: SRResize
        imgH: 32
        imgW: 128
        down_sample_scale: 2
      - class: SRLabelEncode
      - class: KeepKeys
        keep_keys:
          - img_lr
          - img_hr
          - length
          - input_tensor
          - label
  DataLoader:
    shuffle: false
    batch_size: 16
    drop_last: true
    num_workers: 4
Eval:
  Dataset:
    class: LMDBDataSetSR
    data_dir: ./train_data/srdata/test
    transforms:
      - class: SRResize
        imgH: 32
        imgW: 128
        down_sample_scale: 2
      - class: SRLabelEncode
      - class: KeepKeys
        keep_keys:
          - img_lr
          - img_hr
          - length
          - input_tensor
          - label
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 16
    num_workers: 4
