Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/sr/sr_telescope/
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 1000
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_inference_dir: ./output/sr/sr_telescope/infer
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_52.png
  character_dict_path: null
  max_text_length: 100
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/sr/predicts_telescope.txt
Optimizer:
  class: Adam
  beta1: 0.5
  beta2: 0.999
  clip_norm: 0.25
  lr: 0.0001
LRScheduler: null
Model:
  model_type: sr
  algorithm: Telescope
  Transform:
    class: TBSRN
    STN: true
    infer_mode: false
Loss:
  class: TelescopeLoss
  confuse_dict_path: ./ppocr/utils/dict/confuse.pkl
PostProcessor:
  class: None
Metric:
  class: SRMetric
  main_indicator: all
Train:
  Dataset:
    class: LMDBDataSetSR
    data_dir: ./train_data/TextZoom/train
    transforms:
      - class: SRResize
        imgH: 32
        imgW: 128
        down_sample_scale: 2
      - class: KeepKeys
        keep_keys:
          - img_lr
          - img_hr
          - label
  DataLoader:
    shuffle: false
    batch_size: 16
    drop_last: true
    num_workers: 4
Eval:
  Dataset:
    class: LMDBDataSetSR
    data_dir: ./train_data/TextZoom/test
    transforms:
      - class: SRResize
        imgH: 32
        imgW: 128
        down_sample_scale: 2
      - class: KeepKeys
        keep_keys:
          - img_lr
          - img_hr
          - label
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 16
    num_workers: 4
