Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/cls/mv3/
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 1000
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  label_list:
    - '0'
    - '180'
Model:
  model_type: cls
  algorithm: CLS
  Transform: null
  Backbone:
    class: MobileNetV3
    scale: 0.35
    model_name: small
  Neck: null
  Head:
    class: ClsHead
    class_dim: 2
Loss:
  class: ClsLoss
Optimizer:
  class: Adam
  beta1: 0.9
  beta2: 0.999
  lr: 0.001
LRScheduler:
  class: Cosine
PostProcessor:
  class: ClsPostProcess
Metric:
  class: ClsMetric
  main_indicator: acc
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/cls
    label_file_list:
      - ./train_data/cls/train.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: ClsLabelEncode
      - class: BaseDataAugmentation
      - class: RandAugment
      - class: ClsResizeImg
        image_shape:
          - 3
          - 48
          - 192
      - class: KeepKeys
        keep_keys:
          - image
          - label
  DataLoader:
    shuffle: true
    batch_size: 512
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/cls
    label_file_list:
      - ./train_data/cls/test.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: ClsLabelEncode
      - class: ClsResizeImg
        image_shape:
          - 3
          - 48
          - 192
      - class: KeepKeys
        keep_keys:
          - image
          - label
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 512
    num_workers: 4
