Global:
  use_gpu: true
  epoch_num: 130
  log_window_size: 10
  log_batch_step: 10
  save_model_dir: ./output/re_vi_layoutxlm_xfund_zh
  save_epoch_step: 2000
  eval_batch_step:
    - 0
    - 19
  metric_during_train: false
  save_infer_dir: null
  use_visualdl: false
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_21.jpg
  save_res_path: ./output/re/xfund_zh/with_gt
  kie_rec_model_dir: null
  kie_det_model_dir: null
Model:
  model_type: kie
  algorithm: LayoutXLM
  Transform: null
  Backbone:
    class: LayoutXLMForRe
    pretrained: true
    mode: vi
    checkpoints: null
Loss:
  class: LossFromOutput
  key: loss
  reduction: mean
Optimizer:
  class: AdamW
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10
  lr: 5.0e-05
LRScheduler:
  warmup_epoch: 10
PostProcessor:
  class: VQAReTokenLayoutLMPostProcess
Metric:
  class: VQAReTokenMetric
  main_indicator: hmean
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: train_data/XFUND/zh_train/image
    label_file_list:
      - train_data/XFUND/zh_train/train.json
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: VQATokenLabelEncode
        contains_re: true
        algorithm: LayoutXLM
        class_path: train_data/XFUND/class_list_xfun.txt
        use_textline_bbox_info: true
        order_method: tb-yx
      - class: VQATokenPad
        max_seq_len: 512
        return_attention_mask: true
      - class: VQAReTokenRelation
      - class: VQAReTokenChunk
        max_seq_len: 512
      - class: TensorizeEntitiesRelations
      - class: Resize
        size:
          - 224
          - 224
      - class: NormalizeImage
        scale: 1
        mean:
          - 123.675
          - 116.28
          - 103.53
        std:
          - 58.395
          - 57.12
          - 57.375
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - input_ids
          - bbox
          - attention_mask
          - token_type_ids
          - entities
          - relations
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 2
    num_workers: 4
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: train_data/XFUND/zh_val/image
    label_file_list:
      - train_data/XFUND/zh_val/val.json
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: VQATokenLabelEncode
        contains_re: true
        algorithm: LayoutXLM
        class_path: train_data/XFUND/class_list_xfun.txt
        use_textline_bbox_info: true
        order_method: tb-yx
      - class: VQATokenPad
        max_seq_len: 512
        return_attention_mask: true
      - class: VQAReTokenRelation
      - class: VQAReTokenChunk
        max_seq_len: 512
      - class: TensorizeEntitiesRelations
      - class: Resize
        size:
          - 224
          - 224
      - class: NormalizeImage
        scale: 1
        mean:
          - 123.675
          - 116.28
          - 103.53
        std:
          - 58.395
          - 57.12
          - 57.375
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - input_ids
          - bbox
          - attention_mask
          - token_type_ids
          - entities
          - relations
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 8
    num_workers: 8
