Global:
  use_gpu: true
  epoch_num: 200
  log_window_size: 10
  log_batch_step: 10
  save_model_dir: ./output/ser_vi_layoutxlm_xfund_zh_udml
  save_epoch_step: 2000
  eval_batch_step:
    - 0
    - 19
  metric_during_train: false
  save_infer_dir: null
  use_visualdl: false
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_42.jpg
  save_res_path: ./output/ser_layoutxlm_xfund_zh/res
Model:
  model_type: kie
  class: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained: null
      freeze_params: false
      return_all_feats: true
      model_type: kie
      algorithm: LayoutXLM
      Transform: null
      Backbone:
        class: LayoutXLMForSer
        pretrained: true
        mode: vi
        checkpoints: null
        num_classes: 7
    Student:
      pretrained: null
      freeze_params: false
      return_all_feats: true
      model_type: kie
      algorithm: LayoutXLM
      Transform: null
      Backbone:
        class: LayoutXLMForSer
        pretrained: true
        mode: vi
        checkpoints: null
        num_classes: 7
Loss:
  class: CombinedLoss
  loss_config_list:
    - DistillationVQASerTokenLayoutLMLoss:
        weight: 1.0
        model_name_list:
          - Student
          - Teacher
        key: backbone_out
        num_classes: 7
    - DistillationSERDMLLoss:
        weight: 1.0
        act: softmax
        use_log: true
        model_name_pairs:
          - - Student
            - Teacher
        key: backbone_out
    - DistillationVQADistanceLoss:
        weight: 0.5
        mode: l2
        model_name_pairs:
          - - Student
            - Teacher
        key: hidden_states_5
        class: loss_5
    - DistillationVQADistanceLoss:
        weight: 0.5
        mode: l2
        model_name_pairs:
          - - Student
            - Teacher
        key: hidden_states_8
        class: loss_8
Optimizer:
  class: AdamW
  beta1: 0.9
  beta2: 0.999
  lr: 5.0e-05
LRScheduler:
  class: PolynomialLR
  total_iters: 200
  warmup_epoch: 10
PostProcessor:
  class: DistillationSerPostProcess
  model_name:
    - Student
    - Teacher
  key: backbone_out
  class_path: train_data/XFUND/class_list_xfun.txt
Metric:
  class: DistillationMetric
  base_metric_name: VQASerTokenMetric
  main_indicator: hmean
  key: Student
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: train_data/XFUND/zh_train/image
    label_file_list:
      - train_data/XFUND/zh_train/train.json
    ratio_list:
      - 1.0
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: VQATokenLabelEncode
        contains_re: false
        algorithm: LayoutXLM
        class_path: train_data/XFUND/class_list_xfun.txt
        order_method: tb-yx
      - class: VQATokenPad
        max_seq_len: 512
        return_attention_mask: true
      - class: VQASerTokenChunk
        max_seq_len: 512
      - class: Resize
        size:
          - 224
          - 224
      - class: NormalizeImage
        scale: 1
        mean:
          - 123.675
          - 116.28
          - 103.53
        std:
          - 58.395
          - 57.12
          - 57.375
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - input_ids
          - bbox
          - attention_mask
          - token_type_ids
          - image
          - labels
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 4
    num_workers: 4
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: train_data/XFUND/zh_val/image
    label_file_list:
      - train_data/XFUND/zh_val/val.json
    transforms:
      - class: DecodeImage
        img_mode: RGB
        channel_first: false
      - class: VQATokenLabelEncode
        contains_re: false
        algorithm: LayoutXLM
        class_path: train_data/XFUND/class_list_xfun.txt
        order_method: tb-yx
      - class: VQATokenPad
        max_seq_len: 512
        return_attention_mask: true
      - class: VQASerTokenChunk
        max_seq_len: 512
      - class: Resize
        size:
          - 224
          - 224
      - class: NormalizeImage
        scale: 1
        mean:
          - 123.675
          - 116.28
          - 103.53
        std:
          - 58.395
          - 57.12
          - 57.375
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - input_ids
          - bbox
          - attention_mask
          - token_type_ids
          - image
          - labels
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 8
    num_workers: 4
