Global:
  debug: false
  use_gpu: true
  epoch_num: 800
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/rec_pp-OCRv2_distillation
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_pp-OCRv2_distillation.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
LRScheduler:
  class: Piecewise
  decay_epochs:
    - 700
  values:
    - 0.001
    - 0.0001
  warmup_epoch: 5
Model:
  model_type: rec
  class: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained: null
      freeze_params: false
      return_all_feats: true
      model_type: rec
      algorithm: CRNN
      Transform: null
      Backbone:
        class: MobileNetV1Enhance
        scale: 0.5
      Neck:
        class: SequenceEncoder
        encoder_type: rnn
        hidden_size: 64
      Head:
        class: CTCHead
        mid_channels: 96
        fc_decay: 2.0e-05
    Student:
      pretrained: null
      freeze_params: false
      return_all_feats: true
      model_type: rec
      algorithm: CRNN
      Transform: null
      Backbone:
        class: MobileNetV1Enhance
        scale: 0.5
      Neck:
        class: SequenceEncoder
        encoder_type: rnn
        hidden_size: 64
      Head:
        class: CTCHead
        mid_channels: 96
        fc_decay: 2.0e-05
Loss:
  class: CombinedLoss
  loss_config_list:
    - DistillationCTCLoss:
        weight: 1.0
        model_name_list:
          - Student
          - Teacher
        key: head_out
    - DistillationDMLLoss:
        weight: 1.0
        act: softmax
        use_log: true
        model_name_pairs:
          - - Student
            - Teacher
        key: head_out
    - DistillationDistanceLoss:
        weight: 1.0
        mode: l2
        model_name_pairs:
          - - Student
            - Teacher
        key: backbone_out
PostProcessor:
  class: DistillationCTCLabelDecode
  model_name:
    - Student
    - Teacher
  key: head_out
Metric:
  class: DistillationMetric
  base_metric_name: RecMetric
  main_indicator: acc
  key: Student
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/train_list.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: RecAug
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 320
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 128
    drop_last: true
    num_sections: 1
    num_workers: 8
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data
    label_file_list:
      - ./train_data/val_list.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 320
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 128
    num_workers: 8
