Global:
  debug: false
  use_gpu: true
  epoch_num: 800
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/rec_mobile_pp-OCRv2_enhanced_ctc_loss
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ptocr/utils/ppocr_keys_v1.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_mobile_pp-OCRv2_enhanced_ctc_loss.txt
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
LRScheduler:
  class: PiecewiseLR
  decay_epochs:
    - 700
  values:
    - 0.001
    - 0.0001
  warmup_epoch: 5
Model:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    class: MobileNetV1Enhance
    scale: 0.5
  Neck:
    class: SequenceEncoder
    encoder_type: rnn
    hidden_size: 64
  Head:
    class: CTCHead
    mid_channels: 96
    fc_decay: 2.0e-05
    return_feats: true
Loss:
  class: CombinedLoss
  loss_config_list:
    - CTCLoss:
        use_focal_loss: false
        weight: 1.0
    - CenterLoss:
        weight: 0.05
        num_classes: 6625
        feat_dim: 96
        center_file_path: null
PostProcessor:
  class: CTCLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: SimpleDataSet
    root: ./train_data/
    label_file_list:
      - ./train_data/train_list.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: RecAug
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 320
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
          - label_ace
  DataLoader:
    shuffle: true
    batch_size: 128
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: SimpleDataSet
    root: ./train_data
    label_file_list:
      - ./train_data/val_list.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 320
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 128
    num_workers: 8
