Global:
  use_gpu: true
  epoch_num: 500
  log_window_size: 20
  log_batch_step: 10
  save_model_dir: ./output/rec_en_number_lite
  save_epoch_step: 3
  eval_batch_step:
    - 0
    - 2000
  metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_infer_dir: null
  use_visualdl: false
  infer_img: null
  character_dict_path: ppocr/utils/en_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
Optimizer:
  class: Adam
  betas: 
    - 0.9
    - 0.999
  lr: 0.001
LRScheduler:
  class: CosineAnnealingLR
  # T_max: null
Model:
  model_type: rec
  algorithm: CRNN
  Transform: null
  Backbone:
    class: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride:
      - 1
      - 2
      - 2
      - 2
  Neck:
    class: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    class: CTCHead
    fc_decay: 1.0e-05
Loss:
  class: CTCLoss
PostProcessor:
  class: CTCLabelDecode
Metric:
  class: RecMetric
  main_indicator: acc
Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/train_list.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: RecAug
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 320
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: true
    batch_size: 256
    drop_last: true
    num_workers: 8
Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
      - ./train_data/eval_list.txt
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: CTCLabelEncode
      - class: RecResizeImg
        image_shape:
          - 3
          - 32
          - 320
      - class: KeepKeys
        keep_keys:
          - image
          - label
          - length
  DataLoader:
    shuffle: false
    drop_last: false
    batch_size: 256
    num_workers: 8
