Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/ch_PP-OCR_v3_det/
  save_epoch_step: 100
  eval_batch_step:
    - 0
    - 400
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
  distributed: true

Model:
  class: DistillationModel
  algorithm: Distillation
  model_type: det
  Models:
    Student:
      pretrained:
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        class: MobileNetV3
        scale: 0.5
        model_name: large
        disable_se: true
      Neck:
        class: RSEFPN
        out_channels: 96
        shortcut: True
      Head:
        class: DBHead
        k: 50
    Student2:
      pretrained:
      model_type: det
      algorithm: DB
      Transform: null
      Backbone:
        class: MobileNetV3
        scale: 0.5
        model_name: large
        disable_se: true
      Neck:
        class: RSEFPN
        out_channels: 96
        shortcut: True
      Head:
        class: DBHead
        k: 50
    Teacher:
      freeze_params: true
      return_all_feats: false
      model_type: det
      algorithm: DB
      Backbone:
        class: ResNet_vd
        in_channels: 3
        layers: 50
      Neck:
        class: LKPAN
        out_channels: 256
      Head:
        class: DBHead
        kernel_list: [ 7,2,2 ]
        k: 50

Loss:
  class: CombinedLoss
  loss_config_list:
    - DistillationDilaDBLoss:
        weight: 1.0
        model_name_pairs:
          - [ "Student", "Teacher" ]
          - [ "Student2", "Teacher" ]
        key: maps
        balance_loss: true
        main_loss_type: DiceLoss
        alpha: 5
        beta: 10
        ohem_ratio: 3
    - DistillationDMLLoss:
        model_name_pairs:
          - [ "Student", "Student2" ]
        maps_name: "thrink_maps"
        weight: 1.0
        model_name_pairs: [ "Student", "Student2" ]
        key: maps
    - DistillationDBLoss:
        weight: 1.0
        model_name_list: [ "Student", "Student2" ]
        balance_loss: true
        main_loss_type: DiceLoss
        alpha: 5
        beta: 10
        ohem_ratio: 3

Optimizer:
  class: Adam
  beta1: 0.9
  beta2: 0.999
  lr: 0.001
LRScheduler:
  class: Cosine
  
  warmup_epoch: 2


PostProcessor:
  class: DistillationDBPostProcess
  model_name: [ "Student" ]
  key: head_out
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  class: DistillationMetric
  base_metric_name: DetMetric
  main_indicator: hmean
  key: "Student"

Train:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list: [ 1.0 ]
    transforms:
      - class: DecodeImage
        img_mode: BGR
        channel_first: false
      - class: DetLabelEncode null
      - class: CopyPaste
      - class: IaaAugment
        augmenter_args:
          - type: Fliplr
            args:
              p: 0.5
          - type: Affine
            args:
              rotate:
                - -10
                - 10
          - type: Resize
            args:
              size:
                - 0.5
                - 3
      - class: EastRandomCropData
        size:
          - 960
          - 960
        max_tries: 50
        keep_ratio: true
      - class: MakeBorderMap
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
      - class: MakeShrinkMap
        shrink_ratio: 0.4
        min_text_size: 8
      - class: NormalizeImage
        scale: 1./255.
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
        order: hwc
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys:
          - image
          - threshold_map
          - threshold_mask
          - shrink_map
          - shrink_mask
  DataLoader:
    shuffle: true
    drop_last: false
    batch_size: 8
    num_workers: 4

Eval:
  Dataset:
    class: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/test_icdar2015_label.txt
    transforms:
      - class: DecodeImage # load image
        img_mode: BGR
        channel_first: False
      - class: DetLabelEncode # Class handling label
      - class: DetResizeForTest
      - class: NormalizeImage
        scale: 1./255.
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
        order: 'hwc'
      - class: ToCHWImage
      - class: KeepKeys
        keep_keys: [ 'image', 'shape', 'polys', 'ignore_tags' ]
  DataLoader:
    shuffle: False
    drop_last: False
    batch_size: 1 # must be 1
    num_workers: 2
